"""translate-proxy — transparent translation relay for LLM coding agents.

Sits between an AI client (Claude Code, opencode, Hermes, ...) and the model
endpoint it already uses. Rewrites the user's language (USER_LANG) into the
model's language (MODEL_LANG) on the way in, and translates the model's answer
back to USER_LANG on the way out with a cheap, configurable translator model.

Python standard library only. Bind to 127.0.0.1.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import hmac
import json
import os
import re
import sys
import threading
import urllib.error
import urllib.parse
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer


def load_dotenv(path=None):
    """Load KEY=VALUE pairs from a .env file into os.environ. Stdlib, no deps.

    Lets users keep API keys in a gitignored .env file instead of exporting
    them: create .env, paste your keys, run. Real environment variables always
    win — a key already set in the shell is never overwritten. A missing file
    is fine (no-op). Looked up next to this script, then in the current
    directory; an absolute path is used as-is.
    """
    target = _find_env_file(path)
    if target is None:
        return
    try:
        with open(target, encoding="utf-8") as f:
            _apply_dotenv(f.read())
    except OSError:
        return


def _env_candidates(path):
    if path is None:
        path = ".env"
    if os.path.isabs(path):
        return [path]
    script_dir = os.path.dirname(os.path.abspath(__file__))
    return [os.path.join(script_dir, path), os.path.join(os.getcwd(), path)]


def _find_env_file(path):
    return next((c for c in _env_candidates(path) if os.path.isfile(c)), None)


def _parse_dotenv(text):
    """Yield (key, value) pairs from .env text.

    Skips blank lines and # comments; tolerates an `export ` prefix, single or
    double quotes around the value, and a trailing ` # comment`.
    """
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export "):].lstrip()
        key, sep, value = line.partition("=")
        key = key.strip()
        if not sep or not key:
            continue
        value = value.strip()
        if value.startswith("#"):  # KEY=  # comment -> empty value
            value = ""
        elif len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
            value = value[1:-1]  # quoted value, kept as-is
        else:
            comment = value.find(" #")
            if comment != -1:
                value = value[:comment].rstrip()
        yield key, value


def _apply_dotenv(text):
    for key, value in _parse_dotenv(text):
        if key not in os.environ:
            os.environ[key] = value


try:
    from cryptography.fernet import Fernet, InvalidToken
    from cryptography.hazmat.primitives import hashes
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    _HAVE_CRYPTO = True
except ImportError:
    _HAVE_CRYPTO = False

_ENV_ENC_FILE = ".env.enc"
_ENV_PASSPHRASE_VAR = "ENV_PASSPHRASE"
_PBKDF2_ITERATIONS = 600_000


def _script_dir():
    return os.path.dirname(os.path.abspath(__file__))


_ENV_TEMPLATE = os.path.join(_script_dir(), ".env.example")
_DEFAULT_ENV_TEMPLATE = (
    "# Keys for translate-proxy (auto-generated by the proxy — fill these in).\n"
    "USER_LANG=pl\n"
    "MODEL_LANG=en\n"
    "TRANSLATOR=deepseek\n"
    "TRANSLATOR_MODEL=deepseek-v4-flash\n"
    "DEEPSEEK_API_KEY=\n"
)


def _ensure_env_file(path=".env", dest_dir=None):
    """Create .env from the shipped template when neither .env nor .env.enc exists.

    First run of the proxy makes the file for you — you only paste keys. Returns
    the created path, or None when .env already exists, an encrypted .env is in
    place (a plaintext beside it would defeat it), or creation fails.
    """
    if _find_env_file(path) is not None:
        return None
    if _find_env_file(_ENV_ENC_FILE) is not None:
        return None
    if os.path.isfile(_ENV_TEMPLATE):
        try:
            with open(_ENV_TEMPLATE, encoding="utf-8") as f:
                content = f.read()
        except OSError:
            content = _DEFAULT_ENV_TEMPLATE
    else:
        content = _DEFAULT_ENV_TEMPLATE
    dest = os.path.join(dest_dir or _script_dir(), path)
    try:
        with open(dest, "w", encoding="utf-8") as f:
            f.write(content)
    except OSError:
        return None
    return dest


def _fernet_key(passphrase, salt):
    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(), length=32, salt=salt, iterations=_PBKDF2_ITERATIONS
    )
    return Fernet(base64.urlsafe_b64encode(kdf.derive(passphrase.encode("utf-8"))))


def _hash_passphrase(passphrase, salt):
    """One-way PBKDF2-HMAC-SHA256 hash of the passphrase — stored for
    verification only, so a leaked .env.enc still cannot reveal the passphrase."""
    return hashlib.pbkdf2_hmac("sha256", passphrase.encode("utf-8"), salt, _PBKDF2_ITERATIONS)


def _serialize_env_enc(verif_salt, verif_hash, enc_salt, token):
    return (verif_salt.hex() + ":" + verif_hash.hex()
            + ":" + enc_salt.hex() + ":" + token.decode("ascii"))


def _parse_env_enc(payload):
    parts = payload.split(":")
    if len(parts) < 4:
        raise ValueError("corrupted .env.enc")
    return (bytes.fromhex(parts[0]), parts[1],
            bytes.fromhex(parts[2]), ":".join(parts[3:]).encode("ascii"))


def _decrypt_env_enc_payload(payload, passphrase):
    """Verify the passphrase against its stored hash, then Fernet-decrypt."""
    verif_salt, verif_hash, enc_salt, token = _parse_env_enc(payload)
    if not hmac.compare_digest(_hash_passphrase(passphrase, verif_salt).hex(), verif_hash):
        raise ValueError("wrong passphrase — could not decrypt .env.enc")
    try:
        return _fernet_key(passphrase, enc_salt).decrypt(token)
    except InvalidToken:
        raise ValueError("wrong passphrase — could not decrypt .env.enc")


def _passphrase(confirm=False):
    pw = os.environ.get(_ENV_PASSPHRASE_VAR)
    if pw:
        return pw
    import getpass
    if confirm:
        pw1 = getpass.getpass("passphrase for .env.enc: ")
        pw2 = getpass.getpass("repeat passphrase: ")
        if pw1 != pw2:
            raise ValueError("passphrases do not match")
        return pw1
    return getpass.getpass("passphrase: ")


def encrypt_env_file(src=".env", dst=_ENV_ENC_FILE):
    """Encrypt a plaintext .env into dst (Fernet + PBKDF2-SHA256, 600k iters).

    The passphrase is never stored: a PBKDF2 hash is written for verification
    and the Fernet key is derived from the passphrase at decrypt time. The
    source file is left untouched — after verifying the proxy starts, remove
    it yourself so no plaintext remains.
    """
    if not _HAVE_CRYPTO:
        raise RuntimeError("--make-env-enc needs `pip install cryptography` (optional)")
    if not os.path.isfile(src):
        raise FileNotFoundError(f"no {src} to encrypt")
    with open(src, encoding="utf-8") as f:
        plaintext = f.read()
    pw = _passphrase(confirm=True)
    verif_salt = os.urandom(16)
    verif_hash = _hash_passphrase(pw, verif_salt)
    enc_salt = os.urandom(16)
    token = _fernet_key(pw, enc_salt).encrypt(plaintext.encode("utf-8"))
    with open(dst, "w", encoding="utf-8") as f:
        f.write(f"# {dst} — encrypted .env (Fernet + PBKDF2). Unlock with {_ENV_PASSPHRASE_VAR}.\n")
        f.write(_serialize_env_enc(verif_salt, verif_hash, enc_salt, token) + "\n")
    return dst


def decrypt_env_file(src=_ENV_ENC_FILE, dst=".env"):
    """Decrypt src back to plaintext dst (for editing keys)."""
    if not _HAVE_CRYPTO:
        raise RuntimeError("--env-decrypt needs `pip install cryptography` (optional)")
    if not os.path.isfile(src):
        raise FileNotFoundError(f"no {src} to decrypt")
    with open(src, encoding="utf-8") as f:
        payload = next((ln for ln in f.read().splitlines() if ln.strip() and not ln.startswith("#")), "")
    plaintext = _decrypt_env_enc_payload(payload, _passphrase())
    with open(dst, "w", encoding="utf-8") as f:
        f.write(plaintext.decode("utf-8"))
    return dst


def _load_dotenv_enc(path=_ENV_ENC_FILE):
    """Decrypt .env.enc into os.environ in memory — never writes plaintext.

    Only meaningful when there is no plaintext .env. A daemon cannot prompt
    interactively, so it needs ENV_PASSPHRASE set. Wrong passphrase -> warning
    and skip (the proxy still starts; keys are simply absent).
    """
    if not _HAVE_CRYPTO:
        return
    target = _find_env_file(path)
    if target is None:
        return
    try:
        with open(target, encoding="utf-8") as f:
            payload = next((ln for ln in f.read().splitlines() if ln.strip() and not ln.startswith("#")), "")
    except OSError:
        return
    passphrase = os.environ.get(_ENV_PASSPHRASE_VAR)
    if not passphrase:
        print(f"[translate-proxy] warning: {target} found but {_ENV_PASSPHRASE_VAR} "
              "is not set — not loading it", file=sys.stderr)
        return
    try:
        plaintext = _decrypt_env_enc_payload(payload, passphrase)
    except ValueError as e:
        print(f"[translate-proxy] warning: {target} could not be decrypted ({e})", file=sys.stderr)
        return
    _apply_dotenv(plaintext.decode("utf-8"))


VERSION = "0.1.0"

LANG_NAMES = {
    "pl": "Polish", "en": "English", "de": "German", "fr": "French", "es": "Spanish",
    "it": "Italian", "uk": "Ukrainian", "ru": "Russian", "cs": "Czech", "nl": "Dutch",
    "sv": "Swedish", "da": "Danish", "no": "Norwegian", "fi": "Finnish", "pt": "Portuguese",
    "tr": "Turkish", "hu": "Hungarian", "ro": "Romanian", "sk": "Slovak", "bg": "Bulgarian",
    "el": "Greek", "hr": "Croatian", "sr": "Serbian", "lt": "Lithuanian", "lv": "Latvian",
    "et": "Estonian", "sl": "Slovenian",
    # every-language UX: USER_LANG alone should name the language; obscure codes
    # not listed here fall back to the code itself (or set USER_LANG_NAME).
    "zh": "Chinese", "ja": "Japanese", "ko": "Korean", "ar": "Arabic", "he": "Hebrew",
    "hi": "Hindi", "bn": "Bengali", "ur": "Urdu", "pa": "Punjabi", "ta": "Tamil",
    "te": "Telugu", "mr": "Marathi", "gu": "Gujarati", "kn": "Kannada", "ml": "Malayalam",
    "ne": "Nepali", "si": "Sinhala", "th": "Thai", "vi": "Vietnamese",
    "id": "Indonesian", "ms": "Malay", "tl": "Filipino", "km": "Khmer", "my": "Burmese",
    "lo": "Lao", "mn": "Mongolian", "jv": "Javanese", "ceb": "Cebuano",
    "mi": "Maori", "haw": "Hawaiian", "sm": "Samoan", "fj": "Fijian",
    "sw": "Swahili", "am": "Amharic", "ha": "Hausa", "yo": "Yoruba", "ig": "Igbo",
    "zu": "Zulu", "xh": "Xhosa", "af": "Afrikaans", "so": "Somali", "mg": "Malagasy",
    "wo": "Wolof", "rw": "Kinyarwanda", "sn": "Shona", "st": "Sesotho", "tn": "Tswana",
    "ee": "Ewe", "ak": "Akan", "ti": "Tigrinya", "om": "Oromo",
    "fa": "Persian", "ps": "Pashto", "ku": "Kurdish", "uz": "Uzbek", "kk": "Kazakh",
    "az": "Azerbaijani", "hy": "Armenian", "ka": "Georgian", "tg": "Tajik",
    "tk": "Turkmen", "ky": "Kyrgyz",
    "cy": "Welsh", "ga": "Irish", "gd": "Scottish Gaelic", "mt": "Maltese",
    "sq": "Albanian", "mk": "Macedonian", "be": "Belarusian", "is": "Icelandic",
    "bs": "Bosnian", "ca": "Catalan", "gl": "Galician", "eu": "Basque",
    "lb": "Luxembourgish", "fy": "Frisian",
}


def lang_name(code: str) -> str:
    """Human-readable language name for a code, falling back to the code itself."""
    return LANG_NAMES.get(code, code)


def parse_bool(v, default: bool = False) -> bool:
    if v is None:
        return default
    return str(v).strip().lower() in ("1", "true", "yes", "on")


BACKENDS = {
    # name -> (default OpenAI chat/completions URL, default model, key env var or None)
    "openrouter": ("https://openrouter.ai/api/v1/chat/completions", "deepseek/deepseek-v4-flash", "OPENROUTER_API_KEY"),
    "deepseek": ("https://api.deepseek.com/chat/completions", "deepseek-v4-flash", "DEEPSEEK_API_KEY"),
    "cerebras": (None, "gpt-oss-120b", None),  # URL comes from CEREBRAS_BASE (+ /chat/completions)
    # machine-translation backends: no model, no prompt — the raw text + lang codes go straight to the API
    "google": ("https://translation.googleapis.com/language/translate/v2", "", "GOOGLE_TRANSLATE_API_KEY"),
    "libretranslate": (None, "", None),  # URL comes from LIBRETRANSLATE_BASE (+ /translate), optional key via LIBRETRANSLATE_API_KEY
    "deepl": (None, "", "DEEPL_API_KEY"),  # URL from DEEPL_API_BASE (default api-free.deepl.com/v2) + /translate
    "azure": (None, "", "AZURE_TRANSLATOR_KEY"),  # api.cognitive.microsofttranslator.com; region via AZURE_TRANSLATOR_REGION
}

# machine-translation backends have NO implicit fallback: the user's TRANSLATOR
# choice is authoritative, so a free pick never silently switches to a paid LLM
MACHINE_BACKENDS = {"google", "libretranslate", "deepl", "azure"}


def parse_fallback(s: str):
    """'deepseek/deepseek-v4-flash, cerebras' -> [('deepseek','deepseek-v4-flash'), ('cerebras','gpt-oss-120b')]"""
    out = []
    for part in (s or "").split(","):
        part = part.strip()
        if not part:
            continue
        if "/" in part:
            backend, model = part.split("/", 1)
            out.append((backend.strip(), model.strip()))
        else:
            model = BACKENDS[part][1] if part in BACKENDS else ""
            out.append((part, model))
    return out


class Config:
    def __init__(self, port, upstream, verbose, placeholder, user_lang, user_lang_name,
                 model_lang, model_lang_name, translator, translator_model, translator_fallback,
                 translate_history, cache_size, guard_ratio, translator_timeout, upstream_timeout,
                 cerebras_base, libretranslate_base=None, skip_translation_models=None,
                 stop_requested=False, health_only=False, stop_file=None):
        self.port = port
        self.upstream = upstream
        self.verbose = verbose
        self.placeholder = placeholder
        self.user_lang = user_lang
        self.user_lang_name = user_lang_name
        self.model_lang = model_lang
        self.model_lang_name = model_lang_name
        self.translator = translator
        self.translator_model = translator_model
        self.translator_fallback = translator_fallback
        self.translate_history = translate_history
        self.cache_size = cache_size
        self.guard_ratio = guard_ratio
        self.translator_timeout = translator_timeout
        self.upstream_timeout = upstream_timeout
        self.cerebras_base = cerebras_base
        self.libretranslate_base = libretranslate_base or "http://127.0.0.1:5000"
        self.skip_translation_models = list(skip_translation_models) if skip_translation_models is not None else ["deepseek-v4-flash", "deepseek-pro"]
        self.stop_requested = stop_requested
        self.health_only = health_only
        self.stop_file = stop_file


def load_config(argv=None) -> Config:
    ap = argparse.ArgumentParser(
        prog="translate-proxy",
        description="Translation relay for LLM coding agents (USER_LANG <-> MODEL_LANG).",
    )
    ap.add_argument("--port", type=int, default=int(os.environ.get("PORT", "8800")))
    ap.add_argument("--upstream", default=os.environ.get("UPSTREAM"), help="upstream base URL, e.g. http://127.0.0.1:8799")
    ap.add_argument("--verbose", action="store_true", default=parse_bool(os.environ.get("VERBOSE")))
    ap.add_argument("--placeholder", default=os.environ.get("PLACEHOLDER", "…"))
    ap.add_argument("--stop", action="store_true", help="request the running instance to stop")
    ap.add_argument("--health", action="store_true", help="print GET /health of the running instance")
    args = ap.parse_args(argv)
    # --stop and --health only need the port; upstream is required to serve.
    if not args.upstream and not args.stop and not args.health:
        ap.error("--upstream is required (or UPSTREAM env)")

    user_lang = os.environ.get("USER_LANG", "pl").strip().lower()
    model_lang = os.environ.get("MODEL_LANG", "en").strip().lower()
    # --- translator defaults -------------------------------------------------
    # Default: direct DeepSeek API (https://api.deepseek.com), needs DEEPSEEK_API_KEY.
    # To use OpenRouter instead (one key, many models), set:
    #   TRANSLATOR=openrouter TRANSLATOR_MODEL=deepseek/deepseek-v4-flash
    #   and OPENROUTER_API_KEY. The fallback keeps OpenRouter as a backup route for
    #   the same model — it only activates if OPENROUTER_API_KEY is also set.
    translator = os.environ.get("TRANSLATOR", "deepseek").strip().lower()
    translator_model = os.environ.get("TRANSLATOR_MODEL", BACKENDS[translator][1] if translator in BACKENDS else "")
    # TRANSLATOR is the user's authoritative choice. Implicit fallback is only for
    # LLM backends (the OpenRouter safety net). Machine-translation backends
    # (google/libretranslate/deepl/azure) get NO implicit fallback — a free pick
    # never silently switches to a paid LLM; a fallback only runs if the user
    # explicitly sets TRANSLATOR_FALLBACK.
    fallback_raw = os.environ.get("TRANSLATOR_FALLBACK")
    if fallback_raw is None:
        fallback_raw = "" if translator in MACHINE_BACKENDS else "openrouter/deepseek/deepseek-v4-flash"
    # Main models that pass through untranslated. On cheap models (deepseek-v4-flash,
    # deepseek-pro) the ~1.3x token saving from English doesn't beat the translation
    # cost, so the relay becomes a plain pass-through. Substring match, so both bare
    # names and provider-prefixed ones ("deepseek/deepseek-v4-flash") are caught.
    # Set SKIP_TRANSLATION_MODELS= (empty) to translate for every model.
    skip_raw = os.environ.get("SKIP_TRANSLATION_MODELS", "deepseek-v4-flash,deepseek-pro")
    skip_translation_models = [s.strip().lower() for s in skip_raw.split(",") if s.strip()]

    return Config(
        port=args.port,
        upstream=args.upstream,
        verbose=args.verbose,
        placeholder=args.placeholder,
        user_lang=user_lang,
        user_lang_name=os.environ.get("USER_LANG_NAME", lang_name(user_lang)),
        model_lang=model_lang,
        model_lang_name=os.environ.get("MODEL_LANG_NAME", lang_name(model_lang)),
        translator=translator,
        translator_model=translator_model,
        translator_fallback=parse_fallback(fallback_raw),
        translate_history=parse_bool(os.environ.get("TRANSLATE_HISTORY"), True),
        cache_size=int(os.environ.get("CACHE_SIZE", "500")),
        guard_ratio=float(os.environ.get("GUARD_STOPWORD_RATIO", "0.3")),
        translator_timeout=int(os.environ.get("TRANSLATOR_TIMEOUT", "60")),
        upstream_timeout=int(os.environ.get("UPSTREAM_TIMEOUT", "300")),
        cerebras_base=os.environ.get("CEREBRAS_BASE", "http://127.0.0.1:8001/v1"),
        libretranslate_base=os.environ.get("LIBRETRANSLATE_BASE", "http://127.0.0.1:5000"),
        skip_translation_models=skip_translation_models,
        stop_requested=args.stop,
        health_only=args.health,
        stop_file=f"/tmp/translate-proxy-{args.port}.stop",
    )


_MARK = "⟦"
_MARK_END = "⟧"


def protect(text: str):
    """Extract fenced code blocks, inline code and URLs into ⟦N⟧ placeholders.

    A single left-to-right pass matches each code/URL span OR a literal ⟦N⟧ marker that
    is not inside one (a marker inside a fence/backtick/URL is consumed as part of that
    span). Spans are indexed strictly by appearance order, and re.sub never re-scans an
    inserted placeholder, so:
      - a literal marker inside a code/URL span stays inside the span value and
        round-trips unchanged;
      - a literal marker in prose is wrapped as a span mapping back to itself, so a later
        restore() can never substitute a real code/URL span into it — its literal index
        value never collides with a generated placeholder's index because indices are
        positional, not derived from the marker text.
    """
    spans = []

    def repl(m):
        if m.group(1) is not None:
            spans.append(m.group(0))  # literal ⟦N⟧ marker in prose → self-span back to itself
        else:
            spans.append(m.group(0).rstrip(".,;:!?"))
        return f"{_MARK}{len(spans) - 1}{_MARK_END}"

    t = re.sub(
        r"```[\s\S]*?```|`[^`\n]+`|https?://\S+(?<![.,;:!?])|⟦(\d+)⟧",
        repl, text,
    )
    return t, spans


def restore(text: str, spans):
    """Put the extracted spans back where their ⟦N⟧ placeholders are.

    Single-pass substitution so span VALUES are never re-scanned: the old loop's
    str.replace re-matched placeholders that appeared inside already-inserted span values.
    """
    def repl(m):
        i = int(m.group(1))
        if 0 <= i < len(spans):
            return spans[i]
        return m.group(0)  # unknown/missing span → leave the marker as-is (best effort)
    return re.sub(rf"{_MARK}(\d+){_MARK_END}", repl, text)


STOPWORDS_EN = frozenset("""a an and are as at be but by did do does for from had has have he her his
i if in is it its me my not of on or our she so that the their them then there these they this to
was we were what when where which who will with you your""".split())


def guard_skip(text: str, cfg: Config) -> bool:
    """True when text already looks like MODEL_LANG (English stopword ratio high).

    Requires at least 2 English-stopword hits in addition to the ratio. Short Polish
    phrases like "zrob to" and "co to jest" contain "to" (an English stopword) and would
    otherwise be wrongly skipped by the ratio alone; pasted English (a long block with
    many hits) is still detected.
    """
    if cfg.model_lang != "en":
        return False
    words = re.findall(r"[a-zA-Z]+", text.lower())
    if not words:
        return False
    hits = sum(1 for w in words if w in STOPWORDS_EN)
    return hits >= 2 and (hits / len(words)) >= cfg.guard_ratio


def should_translate_model(model, cfg):
    """True unless the main model is on the pass-through (cheap) list.

    Substring match, case-insensitive, so both bare names ("deepseek-v4-flash")
    and provider-prefixed ones ("deepseek/deepseek-v4-flash") are caught.
    """
    if not model:
        return True
    m = str(model).strip().lower()
    for skip in cfg.skip_translation_models:
        if skip and skip in m:
            return False
    return True


class TranslatorError(Exception):
    pass


_cache = {}
_cache_lock = threading.Lock()


def _cache_get(key):
    with _cache_lock:
        return _cache.get(key)


def _cache_put(key, value, cap):
    if cap <= 0:
        return  # cache disabled (mirrors functools.lru_cache(maxsize=0))
    with _cache_lock:
        if key not in _cache and len(_cache) >= cap:
            _cache.pop(next(iter(_cache)))  # FIFO eviction of the oldest entry
        _cache[key] = value


def clear_cache():
    with _cache_lock:
        _cache.clear()


def build_prompt(src_name, dst_name, direction="ingress"):
    guard = ("The input may be written without diacritics (e.g. Polish without ą/ę/ś) — "
             "reconstruct the intended words, do not translate letter-by-letter. ")
    if direction == "egress":
        head = f"Translate the following {src_name} text into {dst_name}, in natural, idiomatic {dst_name}. "
    else:
        head = f"Translate the following {src_name} text into {dst_name}. "
    return (f"You are a professional translator. {head}{guard}"
            "Keep every ⟦N⟧ placeholder exactly as written (they are code blocks, inline code, or "
            "URLs that must not change). Keep URLs, numbers, and technical terms unchanged. "
            "Output only the translation, nothing else.")


def _call_google(text, src, dst, cfg):
    """Google Cloud Translation v2 (NMT). Billed per character; free tier 500K chars/month."""
    key = os.environ.get("GOOGLE_TRANSLATE_API_KEY") or ""
    if not key:
        raise TranslatorError("google: GOOGLE_TRANSLATE_API_KEY not set")
    url = BACKENDS["google"][0] + "?key=" + key
    payload = {"q": text, "source": src, "target": dst, "format": "text"}
    req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"),
                                 headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=cfg.translator_timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        raise TranslatorError(f"google failed: {e}") from e
    try:
        return data["data"]["translations"][0]["translatedText"]
    except (KeyError, IndexError, TypeError) as e:
        raise TranslatorError(f"google returned unexpected payload: {data}") from e


def _call_libretranslate(text, src, dst, cfg):
    """LibreTranslate (self-hosted, free). POST /translate on LIBRETRANSLATE_BASE."""
    url = cfg.libretranslate_base.rstrip("/") + "/translate"
    payload = {"q": text, "source": src, "target": dst}
    key = os.environ.get("LIBRETRANSLATE_API_KEY") or ""
    if key:
        payload["api_key"] = key
    req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"),
                                 headers={"Content-Type": "application/json"}, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=cfg.translator_timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        raise TranslatorError(f"libretranslate failed: {e}") from e
    try:
        return data["translatedText"]
    except (KeyError, TypeError) as e:
        raise TranslatorError(f"libretranslate returned unexpected payload: {data}") from e


def _call_deepl(text, src, dst, cfg):
    """DeepL API v2. Free endpoint api-free.deepl.com (Developer plan: 1M chars
    one-time eval); pro via DEEPL_API_BASE=https://api.deepl.com/v2."""
    key = os.environ.get("DEEPL_API_KEY") or ""
    if not key:
        raise TranslatorError("deepl: DEEPL_API_KEY not set")
    base = (os.environ.get("DEEPL_API_BASE") or "https://api-free.deepl.com/v2").rstrip("/")
    payload = urllib.parse.urlencode({
        "text": text, "source_lang": src.upper(), "target_lang": dst.upper(),
    }).encode("utf-8")
    req = urllib.request.Request(base + "/translate", data=payload,
                                 headers={"Authorization": "DeepL-Auth-Key " + key,
                                          "Content-Type": "application/x-www-form-urlencoded"},
                                 method="POST")
    try:
        with urllib.request.urlopen(req, timeout=cfg.translator_timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        raise TranslatorError(f"deepl failed: {e}") from e
    try:
        return data["translations"][0]["text"]
    except (KeyError, IndexError, TypeError) as e:
        raise TranslatorError(f"deepl returned unexpected payload: {data}") from e


def _call_azure(text, src, dst, cfg):
    """Microsoft Translator (Azure AI Translator) v3. Permanent free tier 2M chars/month."""
    key = os.environ.get("AZURE_TRANSLATOR_KEY") or ""
    if not key:
        raise TranslatorError("azure: AZURE_TRANSLATOR_KEY not set")
    url = ("https://api.cognitive.microsofttranslator.com/translate"
           + "?api-version=3.0&from=" + src + "&to=" + dst)
    headers = {"Ocp-Apim-Subscription-Key": key, "Content-Type": "application/json"}
    region = os.environ.get("AZURE_TRANSLATOR_REGION") or ""
    if region:
        headers["Ocp-Apim-Subscription-Region"] = region
    req = urllib.request.Request(url, data=json.dumps([{"Text": text}]).encode("utf-8"),
                                 headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=cfg.translator_timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        raise TranslatorError(f"azure failed: {e}") from e
    try:
        return data[0]["translations"][0]["text"]
    except (KeyError, IndexError, TypeError) as e:
        raise TranslatorError(f"azure returned unexpected payload: {data}") from e


def _call_backend(backend, model, prompt, user_text, cfg, src=None, dst=None):
    if backend not in BACKENDS:
        raise TranslatorError(f"unknown backend: {backend}")
    # machine-translation backends: raw text + language codes, no prompt/model
    if backend == "google":
        return _call_google(user_text, src, dst, cfg)
    if backend == "libretranslate":
        return _call_libretranslate(user_text, src, dst, cfg)
    if backend == "deepl":
        return _call_deepl(user_text, src, dst, cfg)
    if backend == "azure":
        return _call_azure(user_text, src, dst, cfg)
    url, default_model, key_env = BACKENDS[backend]
    if url is None:
        url = cfg.cerebras_base.rstrip("/") + "/chat/completions"
    if not model:
        model = default_model
    key = os.environ.get(key_env) if key_env else None
    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": prompt},
            {"role": "user", "content": user_text},
        ],
        "temperature": 0.0,
    }
    headers = {"Content-Type": "application/json"}
    if key:
        headers["Authorization"] = "Bearer " + key
    req = urllib.request.Request(url, data=json.dumps(payload).encode("utf-8"), headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req, timeout=cfg.translator_timeout) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except Exception as e:
        raise TranslatorError(f"{backend} failed: {e}") from e
    try:
        return data["choices"][0]["message"]["content"]
    except (KeyError, IndexError, TypeError) as e:
        raise TranslatorError(f"{backend} returned unexpected payload: {data}") from e


def call_with_fallback(prompt, user_text, cfg, call_backend=None, src=None, dst=None):
    """Try the primary backend then each fallback; return first non-empty translation or None."""
    chain = [(cfg.translator, cfg.translator_model)] + list(cfg.translator_fallback)
    for backend, model in chain:
        try:
            out = (call_backend or _call_backend)(backend, model, prompt, user_text, cfg, src=src, dst=dst)
        except TranslatorError as e:
            print(f"[translate-proxy] translator {backend}/{model or 'default'} failed: {e}", file=sys.stderr)
            continue
        if out:
            return out.strip()
    return None


def translate_text(text, cfg, src, dst, direction="ingress", call_backend=None):
    """Translate one text span. Returns the original text when the whole chain fails."""
    if not text or not text.strip():
        return text
    if direction == "ingress" and guard_skip(text, cfg):
        return text
    protected, spans = protect(text)
    key = (src, dst, protected)
    cached = _cache_get(key)
    if cached is not None:
        return restore(cached, spans)
    prompt = build_prompt(lang_name(src), lang_name(dst), direction)
    out = call_with_fallback(prompt, protected, cfg, call_backend, src, dst)
    if out is None:
        return text  # whole chain failed → original
    _cache_put(key, out, cfg.cache_size)
    return restore(out, spans)


def _translate_content(content, cfg, call_backend, src, dst, direction):
    """Translate the text parts of a content value (str or list of blocks).

    Non-text blocks (tool_use, tool_result, thinking, image_url, tool_calls)
    pass through untouched.
    """
    if isinstance(content, str):
        return translate_text(content, cfg, src, dst, direction, call_backend)
    if isinstance(content, list):
        for blk in content:
            if isinstance(blk, dict) and blk.get("type") == "text":
                blk["text"] = translate_text(blk.get("text", ""), cfg, src, dst, direction, call_backend)
        return content
    return content


def translate_anthropic_messages(body, cfg, call_backend=None):
    """Translate user + assistant text (USER_LANG -> MODEL_LANG) in an Anthropic /v1/messages body."""
    # system (string or list of blocks), tools, tool_choice: never touched.
    for msg in body.get("messages", []):
        role = msg.get("role")
        if role not in ("user", "assistant"):
            continue
        if role == "assistant" and not cfg.translate_history:
            continue
        msg["content"] = _translate_content(msg.get("content"), cfg, call_backend,
                                            cfg.user_lang, cfg.model_lang, "ingress")
    return body


def translate_openai_messages(body, cfg, call_backend=None):
    """Translate user + assistant text in an OpenAI /v1/chat/completions body."""
    for msg in body.get("messages", []):
        role = msg.get("role")
        if role not in ("user", "assistant"):
            continue
        if role == "assistant" and not cfg.translate_history:
            continue
        msg["content"] = _translate_content(msg.get("content"), cfg, call_backend,
                                            cfg.user_lang, cfg.model_lang, "ingress")
    return body


def _ev(event, data_dict=None, data_str=None):
    data = data_str if data_str is not None else json.dumps(data_dict, ensure_ascii=False)
    return {"event": event, "data": data}


def parse_sse(raw):
    """bytes -> list of {'event': str|None, 'data': str}"""
    events = []
    for block in raw.decode("utf-8").split("\n\n"):
        block = block.strip()
        if not block:
            continue
        ev = None
        data_lines = []
        for line in block.split("\n"):
            if line.startswith("event:"):
                ev = line[len("event:"):].strip()
            elif line.startswith("data:"):
                data_lines.append(line[len("data:"):].strip())
        events.append({"event": ev, "data": "\n".join(data_lines)})
    return events


def encode_sse(events):
    out = []
    for ev in events:
        lines = []
        if ev.get("event"):
            lines.append("event: " + ev["event"])
        lines.append("data: " + ev["data"])
        out.append("\n".join(lines) + "\n\n")
    return "".join(out).encode("utf-8")


def translate_anthropic_stream(events, cfg, call_backend=None):
    """Buffer each text content block and emit its translation at block stop.

    The placeholder ("…") is intentionally constant: SSE has no delta retraction, so the
    whole response is buffered and a single translated delta is emitted at the end; the fixed
    placeholder signals "translation in progress" while the model's English streams in.
    Non-text blocks (tool_use, etc.) pass through unchanged.
    """
    out = []
    buffer = None
    for ev in events:
        etype = ev.get("event")
        data = None
        if ev.get("data") and ev["data"].lstrip().startswith("{"):
            try:
                data = json.loads(ev["data"])
            except ValueError:
                data = None
        if etype == "content_block_start" and data and data.get("content_block", {}).get("type") == "text":
            buffer = {"index": data["index"], "text": ""}
            out.append(ev)
            if cfg.placeholder:
                d = {"type": "text_delta", "index": buffer["index"], "delta": {"type": "text_delta", "text": cfg.placeholder}}
                out.append(_ev("text_delta", d))
        elif buffer and data and data.get("index") == buffer["index"] and (
            etype == "text_delta"
            or (etype == "content_block_delta" and data.get("delta", {}).get("type") == "text_delta")
        ):
            buffer["text"] += data.get("delta", {}).get("text", "")
        elif etype == "content_block_stop" and buffer and data and data.get("index") == buffer["index"]:
            translated = translate_text(buffer["text"], cfg, cfg.model_lang, cfg.user_lang, "egress", call_backend)
            d = {"type": "text_delta", "index": buffer["index"], "delta": {"type": "text_delta", "text": translated}}
            out.append(_ev("text_delta", d))
            out.append(ev)
            buffer = None
        else:
            out.append(ev)
    if buffer is not None:
        translated = translate_text(buffer["text"], cfg, cfg.model_lang, cfg.user_lang, "egress", call_backend)
        d = {"type": "text_delta", "index": buffer["index"], "delta": {"type": "text_delta", "text": translated}}
        out.append(_ev("text_delta", d))
        out.append(_ev("content_block_stop", {"type": "content_block_stop", "index": buffer["index"]}))
    return out


def translate_openai_stream(chunks, cfg, call_backend=None):
    """Reassemble content deltas and emit the translation as a single chunk.

    The placeholder ("…") is intentionally constant: SSE has no delta retraction, so the
    whole response is buffered and the translation is emitted in one chunk; the fixed
    placeholder signals "translation in progress". tool_calls deltas pass through unchanged,
    between the text chunk and the finish chunk.
    """
    meta = None
    texts = []
    role = None
    finish = None
    usage = None
    tool_calls_chunks = []
    for c in chunks:
        if not isinstance(c, dict):
            continue
        choices = c.get("choices")
        if choices:
            if meta is None:
                meta = {k: v for k, v in c.items() if k != "choices"}
            for ch in choices:
                delta = ch.get("delta") or {}
                if delta.get("role"):
                    role = delta["role"]
                if delta.get("content"):
                    texts.append(delta["content"])
                if delta.get("tool_calls") and not ch.get("finish_reason"):
                    tool_calls_chunks.append(c)
                if ch.get("finish_reason"):
                    finish = c
        if c.get("usage"):
            usage = c
    full = "".join(texts)
    translated = translate_text(full, cfg, cfg.model_lang, cfg.user_lang, "egress", call_backend) if full else ""

    def chunk(content, role=None, finish_reason=None):
        delta = {}
        if role is not None:
            delta["role"] = role
        if content is not None:
            delta["content"] = content
        ch = {"index": 0, "delta": delta}
        if finish_reason is not None:
            ch["finish_reason"] = finish_reason
        return dict(meta, choices=[ch]) if meta else {"choices": [ch]}

    out = []
    if role:
        out.append(chunk("", role=role))
    if full and cfg.placeholder:
        out.append(chunk(cfg.placeholder))
    if translated:
        out.append(chunk(translated))
    out.extend(tool_calls_chunks)
    if finish:
        out.append(finish)
    if usage:
        out.append(usage)
    return out


def translate_anthropic_nonstream(body, cfg, call_backend=None):
    content = body.get("content")
    if content is not None:
        body["content"] = _translate_content(content, cfg, call_backend,
                                             cfg.model_lang, cfg.user_lang, "egress")
    return body


def translate_openai_nonstream(body, cfg, call_backend=None):
    for choice in body.get("choices", []):
        msg = choice.get("message")
        if isinstance(msg, dict):
            msg["content"] = _translate_content(msg.get("content"), cfg, call_backend,
                                                cfg.model_lang, cfg.user_lang, "egress")
    return body

class Handler(BaseHTTPRequestHandler):
    cfg = None
    call_backend = None  # test injection seam: translator callable (backend, model, prompt, text, cfg) -> str
    server_version = "translate-proxy/" + VERSION

    def log_message(self, fmt, *args):
        if self.cfg and self.cfg.verbose:
            super().log_message(fmt, *args)

    def _send(self, status, headers, body):
        self.send_response(status)
        for k, v in headers.items():
            self.send_header(k, v)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        if body:
            self.wfile.write(body)

    def _json(self, status, obj):
        body = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self._send(status, {"Content-Type": "application/json; charset=utf-8"}, body)

    def do_GET(self):
        if self.path == "/health":
            self._json(200, {"ok": True})
            return
        self._json(404, {"error": "not found"})

    def do_POST(self):
        cb = type(self).call_backend  # plain fn, not bound method
        try:
            length = int(self.headers.get("Content-Length") or 0)
            raw = self.rfile.read(length)
            if self.path == "/v1/messages":
                body = json.loads(raw.decode("utf-8"))
                skip = not should_translate_model(body.get("model"), self.cfg)
                if skip:
                    print(f"[translate-proxy] model {body.get('model')!r} on pass-through list — not translating",
                          file=sys.stderr)
                else:
                    body = translate_anthropic_messages(body, self.cfg, call_backend=cb)
                self._forward(self.path, body, bool(body.get("stream")), cb, skip_translation=skip)
            elif self.path == "/v1/chat/completions":
                body = json.loads(raw.decode("utf-8"))
                skip = not should_translate_model(body.get("model"), self.cfg)
                if skip:
                    print(f"[translate-proxy] model {body.get('model')!r} on pass-through list — not translating",
                          file=sys.stderr)
                else:
                    body = translate_openai_messages(body, self.cfg, call_backend=cb)
                self._forward(self.path, body, bool(body.get("stream")), cb, skip_translation=skip)
            else:
                self._json(404, {"error": "unknown path: " + self.path})
        except (ValueError, json.JSONDecodeError) as e:
            self._json(400, {"error": "bad request: " + str(e)})

    def _forward(self, path, body, stream, cb, skip_translation=False):
        url = self.cfg.upstream.rstrip("/") + path
        data = json.dumps(body, ensure_ascii=False).encode("utf-8")
        headers = {
            "Content-Type": "application/json",
            "Accept": self.headers.get("Accept") or "*/*",
        }
        for h in ("Authorization", "X-Api-Key", "Anthropic-Version", "Anthropic-Beta"):
            v = self.headers.get(h)
            if v:
                headers[h] = v
        req = urllib.request.Request(url, data=data, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=self.cfg.upstream_timeout) as resp:
                raw = resp.read()
                ctype = resp.headers.get("Content-Type") or ""
                status = resp.status
        except urllib.error.HTTPError as e:
            try:
                err_body = e.read()
            finally:
                e.close()
            self._send(e.code, {"Content-Type": e.headers.get("Content-Type") or "application/json"}, err_body)
            return
        except Exception as e:
            print(f"[translate-proxy] upstream unreachable: {e}", file=sys.stderr)
            self._json(502, {"error": "upstream unreachable"})
            return
        if skip_translation:
            # Cheap main model — plain relay, response untouched.
            self._send(status, {"Content-Type": ctype or "application/json; charset=utf-8"}, raw)
            return
        if stream and "text/event-stream" in ctype:
            events = parse_sse(raw)
            if self.path == "/v1/messages":
                events = translate_anthropic_stream(events, self.cfg, call_backend=cb)
                self._send(status, {"Content-Type": "text/event-stream; charset=utf-8"}, encode_sse(events))
            else:
                done = any(e.get("data") == "[DONE]" for e in events)
                parsed = [json.loads(e["data"]) for e in events if e.get("data") and e["data"] != "[DONE]"]
                translated = translate_openai_stream(parsed, self.cfg, call_backend=cb)
                out_events = [{"event": None, "data": json.dumps(c, ensure_ascii=False)} for c in translated]
                if done:
                    out_events.append({"event": None, "data": "[DONE]"})
                self._send(status, {"Content-Type": "text/event-stream; charset=utf-8"}, encode_sse(out_events))
        else:
            if self.path == "/v1/messages":
                out = translate_anthropic_nonstream(json.loads(raw.decode("utf-8")), self.cfg, call_backend=cb)
            else:
                out = translate_openai_nonstream(json.loads(raw.decode("utf-8")), self.cfg, call_backend=cb)
            self._send(status, {"Content-Type": ctype or "application/json; charset=utf-8"},
                       json.dumps(out, ensure_ascii=False).encode("utf-8"))


def _serve(server, stop_file):
    print(f"[translate-proxy] listening on http://127.0.0.1:{server.server_port}", file=sys.stderr)
    # A previous --stop may have left a stale stop file behind; clear it so a fresh
    # start on the same port actually serves instead of exiting 0 immediately.
    try:
        os.remove(stop_file)
    except FileNotFoundError:
        pass
    server.timeout = 0.5
    try:
        while not os.path.exists(stop_file):
            server.handle_request()
    finally:
        server.server_close()


def _cmd_make_env_enc():
    src = _find_env_file(".env")
    if src is None:
        created = _ensure_env_file()
        if created:
            print(f"[translate-proxy] no .env — created {created} from the template. "
                  "Fill in your API keys, then run --make-env-enc again.", file=sys.stderr)
            return 1
        print("[translate-proxy] no .env and could not create one", file=sys.stderr)
        return 1
    try:
        dst = encrypt_env_file(src, os.path.join(_script_dir(), _ENV_ENC_FILE))
    except FileNotFoundError:
        print("[translate-proxy] no .env to encrypt", file=sys.stderr)
        return 1
    except RuntimeError as e:
        print(f"[translate-proxy] {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"[translate-proxy] encryption failed: {e}", file=sys.stderr)
        return 1
    print(f"[translate-proxy] wrote {dst} — verify the proxy starts with it, "
          "then `rm .env` to leave no plaintext on disk")
    return 0


def _cmd_env_decrypt():
    src = _find_env_file(_ENV_ENC_FILE)
    if src is None:
        print("[translate-proxy] no .env.enc to decrypt", file=sys.stderr)
        return 1
    try:
        dst = decrypt_env_file(src, os.path.join(_script_dir(), ".env"))
    except RuntimeError as e:
        print(f"[translate-proxy] {e}", file=sys.stderr)
        return 1
    except Exception as e:
        print(f"[translate-proxy] decrypt failed (wrong passphrase?): {e}", file=sys.stderr)
        return 1
    print(f"[translate-proxy] wrote {dst} — edit your keys, re-encrypt with --make-env-enc, then `rm .env`")
    return 0


def main(argv=None):
    raw = list(argv) if argv is not None else sys.argv[1:]
    # .env file helpers — handled before config parsing (they need no upstream).
    if "--make-env-enc" in raw:
        return _cmd_make_env_enc()
    if "--env-decrypt" in raw:
        return _cmd_env_decrypt()
    clean = [a for a in raw if a not in ("--make-env-enc", "--env-decrypt")]
    # First run: if neither .env nor .env.enc exists, make .env from the template.
    if _find_env_file(".env") is None and _find_env_file(_ENV_ENC_FILE) is None:
        created = _ensure_env_file()
        if created:
            print(f"[translate-proxy] created {created} from the template — "
                  "add your API keys there and restart to use them", file=sys.stderr)
    # Load keys: plaintext .env if present, else encrypted .env.enc in memory.
    if _find_env_file(".env") is None:
        _load_dotenv_enc()
    load_dotenv()
    cfg = load_config(clean)
    if cfg.stop_requested:
        open(cfg.stop_file, "w").close()
        print(f"[translate-proxy] stop requested (wrote {cfg.stop_file})")
        return 0
    if cfg.health_only:
        try:
            with urllib.request.urlopen(f"http://127.0.0.1:{cfg.port}/health", timeout=5) as r:
                print(r.read().decode("utf-8"))
                return 0 if r.status == 200 else 1
        except Exception as e:
            print(f"health check failed: {e}", file=sys.stderr)
            return 1
    key_env = BACKENDS[cfg.translator][2] if cfg.translator in BACKENDS else None
    if key_env and not os.environ.get(key_env):
        print(f"[translate-proxy] warning: {key_env} is not set — {cfg.translator} translation "
              "will fall back to the next backend or pass through untranslated", file=sys.stderr)
    Handler.cfg = cfg
    server = ThreadingHTTPServer(("127.0.0.1", cfg.port), Handler)
    _serve(server, cfg.stop_file)
    return 0


if __name__ == "__main__":
    sys.exit(main())
